/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Usuário
 */
public class AdicionarMovimentacao extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarMovimentacao
     */
    public AdicionarMovimentacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tpMovimentacaoTitulo = new javax.swing.JLabel();
        rbEntradaReceitas = new javax.swing.JRadioButton();
        rbSaidaDespesas = new javax.swing.JRadioButton();
        jbVoltarAddMovimentacao = new javax.swing.JButton();
        jbProximoAddMovimentacao = new javax.swing.JButton();
        SelecionarCatDespesa = new javax.swing.JLabel();
        rbAlimentacao = new javax.swing.JRadioButton();
        rbTransporte = new javax.swing.JRadioButton();
        rbAluguel = new javax.swing.JRadioButton();
        rbSaude = new javax.swing.JRadioButton();
        rbEducacao = new javax.swing.JRadioButton();
        rbEntretenimento = new javax.swing.JRadioButton();
        SelecionarCatReceita = new javax.swing.JLabel();
        rbSalario = new javax.swing.JRadioButton();
        rbDecimoTerceiro = new javax.swing.JRadioButton();
        rbFerias = new javax.swing.JRadioButton();
        addBotao = new javax.swing.JButton();
        tfValormovimentacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Adicionar Movimentacao");

        tpMovimentacaoTitulo.setText("Tipo da Movimentacao:");

        rbEntradaReceitas.setText("Entrada de Receita");
        rbEntradaReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEntradaReceitasActionPerformed(evt);
            }
        });

        rbSaidaDespesas.setText("Saida de Despesas");

        jbVoltarAddMovimentacao.setText("VOLTAR");

        jbProximoAddMovimentacao.setText("PRÓXIMO");

        SelecionarCatDespesa.setText("Selecione a categoria: ");

        rbAlimentacao.setText("Alimentação");

        rbTransporte.setText("Transporte");

        rbAluguel.setText("Aluguel");

        rbSaude.setText("Saude");

        rbEducacao.setText("Educação");

        rbEntretenimento.setText("Entretenimento");

        SelecionarCatReceita.setText("Selecione a categoria: ");

        rbSalario.setText("Salario");

        rbDecimoTerceiro.setText("Décimo Terceiro");

        rbFerias.setText("Férias");

        addBotao.setText("ADICIONAR");

        jLabel5.setText("Valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tpMovimentacaoTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbFerias)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfValormovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addBotao)
                                        .addGap(56, 56, 56)
                                        .addComponent(jbVoltarAddMovimentacao)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbProximoAddMovimentacao)
                                        .addGap(132, 132, 132))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(SelecionarCatReceita)
                                                    .addComponent(rbSalario)
                                                    .addComponent(rbDecimoTerceiro))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(rbEntradaReceitas)
                                                .addGap(152, 152, 152)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SelecionarCatDespesa)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbAlimentacao)
                                                    .addComponent(rbSaude))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbTransporte)
                                                    .addComponent(rbEducacao))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(26, 26, 26)
                                                        .addComponent(rbAluguel))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(rbEntretenimento))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(rbSaidaDespesas)
                                                .addGap(160, 160, 160)))
                                        .addGap(93, 93, 93)))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(rbEntradaReceitas)
                        .addGap(18, 18, 18)
                        .addComponent(SelecionarCatReceita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDecimoTerceiro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpMovimentacaoTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rbSaidaDespesas)
                        .addGap(18, 18, 18)
                        .addComponent(SelecionarCatDespesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbAlimentacao)
                            .addComponent(rbTransporte)
                            .addComponent(rbAluguel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbSaude)
                            .addComponent(rbEducacao)
                            .addComponent(rbEntretenimento))))
                .addGap(12, 12, 12)
                .addComponent(rbFerias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbVoltarAddMovimentacao)
                            .addComponent(jbProximoAddMovimentacao))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBotao)
                            .addComponent(tfValormovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbEntradaReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEntradaReceitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEntradaReceitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarMovimentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SelecionarCatDespesa;
    private javax.swing.JLabel SelecionarCatReceita;
    private javax.swing.JButton addBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbProximoAddMovimentacao;
    private javax.swing.JButton jbVoltarAddMovimentacao;
    private javax.swing.JRadioButton rbAlimentacao;
    private javax.swing.JRadioButton rbAluguel;
    private javax.swing.JRadioButton rbDecimoTerceiro;
    private javax.swing.JRadioButton rbEducacao;
    private javax.swing.JRadioButton rbEntradaReceitas;
    private javax.swing.JRadioButton rbEntretenimento;
    private javax.swing.JRadioButton rbFerias;
    private javax.swing.JRadioButton rbSaidaDespesas;
    private javax.swing.JRadioButton rbSalario;
    private javax.swing.JRadioButton rbSaude;
    private javax.swing.JRadioButton rbTransporte;
    private javax.swing.JTextField tfValormovimentacao;
    private javax.swing.JLabel tpMovimentacaoTitulo;
    // End of variables declaration//GEN-END:variables
}
